-- NORTEX - CODIGO 98 DE DESPESA VIRA "AMORTIZAÇÃO"
--
-- Pedido do Marcelo (ticket #10649, 18/08/2026): renomear o codigo 98 de
-- despesa, hoje "OUTROS INVESTIMENTOS", para "AMORTIZAÇÃO".
--
-- Duas partes: atualiza quem ja existe, e corrige o molde para quem nasce
-- depois. So mexe em quem ainda esta com o nome padrao -- se algum cliente ja
-- renomeou o proprio codigo 98 na tela de Codigos, o dele fica como esta.

update codigos_despesa
set nome = 'AMORTIZAÇÃO'
where codigo = 98
  and nome = 'OUTROS INVESTIMENTOS';

-- Recria a funcao de seed identica a 0002_seed_padrao.sql, so com o codigo 98
-- de despesa trocado. O resto (formas de pagamento, tipos de recebimento,
-- tipos de venda, codigos familia, loja matriz) fica exatamente igual.
create or replace function seed_empresa_padrao(p_empresa uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  -- CODIGOS DE DESPESA 1-100
  insert into codigos_despesa (empresa_id, codigo, nome, grupo)
  select p_empresa, c, n, g::grupo_despesa from (values
    (1,'PARTICULAR','PRO_LABORE'),(2,'PARTICULAR','PRO_LABORE'),(3,'PARTICULAR','PRO_LABORE'),(4,'PARTICULAR','PRO_LABORE'),(5,'PARTICULAR','PRO_LABORE'),
    (6,'SALÁRIO','RH_PESSOAL'),(7,'VALES - ADIANTAMENTO SALARIAL','RH_PESSOAL'),(8,'SEGURO DE VIDA','RH_PESSOAL'),(9,'PLR - PARTICIPAÇÕES NOS LUCROS','RH_PESSOAL'),(10,'RESCISÕES','RH_PESSOAL'),
    (11,'MULTA FGTS','RH_PESSOAL'),(12,'FÉRIAS','RH_PESSOAL'),(13,'DÉCIMO TERCEIRO','RH_PESSOAL'),(14,'PROCESSOS TRABALHISTAS','RH_PESSOAL'),(15,'ALIMENTAÇÃO','RH_PESSOAL'),
    (16,'VALE TRANSPORTE','RH_PESSOAL'),(17,'ASSISTÊNCIA MÉDICA - FARMÁCIA','RH_PESSOAL'),(18,'EXAMES MÉDICOS','RH_PESSOAL'),(19,'RECRUTAMENTO - TREINAMENTO','RH_PESSOAL'),(20,'UNIFORMES - EPI','RH_PESSOAL'),
    (21,'MOTOBOY','RH_PESSOAL'),(22,'','RH_PESSOAL'),(23,'FGTS','RH_PESSOAL'),(24,'INSS','RH_PESSOAL'),(25,'OUTRAS DESPESAS DE RH','RH_PESSOAL'),
    (26,'ALUGUEL DE EQUIPAMENTOS','FIXAS'),(27,'GÁS','FIXAS'),(28,'SEGUROS - EMPRESA','FIXAS'),(29,'UBER - APLICATIVOS','FIXAS'),(30,'SOFTWARES - SISTEMAS','FIXAS'),
    (31,'ALUGUEL + CONDOMÍNIO','FIXAS'),(32,'IPTU','FIXAS'),(33,'ÁGUA','FIXAS'),(34,'LUZ','FIXAS'),(35,'TELEFONE FIXO','FIXAS'),
    (36,'TELEFONE MÓVEL','FIXAS'),(37,'INTERNET','FIXAS'),(38,'ADVOGADO','FIXAS'),(39,'CONTADOR','FIXAS'),(40,'CARTÓRIO','FIXAS'),
    (41,'CORREIOS','FIXAS'),(42,'DESPESAS COM VIAGENS','FIXAS'),(43,'HIGIENE E LIMPEZA','FIXAS'),(44,'MATERIAL DE ESCRITÓRIO','FIXAS'),(45,'SINDICATO E ASSOCIAÇÕES','FIXAS'),
    (46,'TAXAS E LICENÇAS','FIXAS'),(47,'MANUTENÇÃO GERAL','FIXAS'),(48,'SEGURANÇA','FIXAS'),(49,'ESTACIONAMENTO','FIXAS'),(50,'COMBUSTÍVEL','FIXAS'),
    (51,'DOCUMENTAÇÃO VEÍCULOS','FIXAS'),(52,'MANUTENÇÃO VEÍCULOS','FIXAS'),(53,'MULTAS VEÍCULOS','FIXAS'),(54,'SEGURO VEÍCULOS','FIXAS'),(55,'PEDÁGIO','FIXAS'),
    (56,'','FIXAS'),(57,'MARKETING','FIXAS'),(58,'CONSULTORIA','FIXAS'),(59,'DEVOLUÇÕES','FIXAS'),(60,'OUTRAS DESPESAS FIXAS','FIXAS'),
    (61,'PIS','IMPOSTOS'),(62,'COFINS','IMPOSTOS'),(63,'ISS','IMPOSTOS'),(64,'ICMS','IMPOSTOS'),(65,'IRPJ','IMPOSTOS'),
    (66,'CSLL','IMPOSTOS'),(67,'DARE','IMPOSTOS'),(68,'DARF','IMPOSTOS'),(69,'TRIBUTOS MOBILIÁRIOS','IMPOSTOS'),(70,'SIMPLES NACIONAL','IMPOSTOS'),
    (71,'EMPRÉSTIMOS','FINANCEIRAS'),(72,'JUROS DE EMPRÉSTIMOS','FINANCEIRAS'),(73,'JUROS E ENCARGOS - CHEQUE ESPECIAL','FINANCEIRAS'),(74,'JUROS E ENCARGOS - FORNECEDORES','FINANCEIRAS'),(75,'ANTECIPAÇÕES - CARTÕES E DUPLICATAS','FINANCEIRAS'),
    (76,'IOF','FINANCEIRAS'),(77,'TARIFAS BANCÁRIAS','FINANCEIRAS'),(78,'ALUGUEL DE MAQUININHA DE CARTÕES','FINANCEIRAS'),(79,'DESCONTOS CONCEDIDOS','FINANCEIRAS'),(80,'OUTRAS DESPESAS FINANCEIRAS','FINANCEIRAS'),
    (81,'','VARIAVEIS'),(82,'COMISSÕES DE VENDEDORES','VARIAVEIS'),(83,'PRÊMIOS POR META - BONIFICAÇÕES','VARIAVEIS'),(84,'FRETES','VARIAVEIS'),(85,'EMBALAGEM - SACOLAS','VARIAVEIS'),
    (86,'TAXAS CARTÃO DÉBITO','VARIAVEIS'),(87,'TAXAS CARTÃO CRÉDITO','VARIAVEIS'),(88,'TAXAS PIX','VARIAVEIS'),(89,'TAXAS CARTÃO ALIMENTAÇÃO','VARIAVEIS'),(90,'OUTRAS DESPESAS VARIÁVEIS','VARIAVEIS'),
    (91,'IMÓVEIS - TERRENOS','INVESTIMENTOS'),(92,'VEÍCULOS','INVESTIMENTOS'),(93,'MÓVEIS E UTENSÍLIOS','INVESTIMENTOS'),(94,'REFORMA','INVESTIMENTOS'),(95,'EQUIPAMENTOS - MÁQUINAS','INVESTIMENTOS'),
    (96,'CONSÓRCIOS','INVESTIMENTOS'),(97,'APLICAÇÕES FINANCEIRAS','INVESTIMENTOS'),(98,'AMORTIZAÇÃO','INVESTIMENTOS'),(99,'RETIRADA SÓCIO','RETIRADA_SOCIO'),(100,'PRODUTOS - INSUMOS - ESTOQUE','ESTOQUE')
  ) as v(c,n,g);

  -- FORMAS DE PAGAMENTO (CP)
  insert into formas_pagamento (empresa_id, codigo, nome)
  select p_empresa, c, n from (values
    (1,'DINHEIRO'),(2,'CHEQUE'),(3,'TÍTULOS / BOLETOS / CARNÊS'),(4,'GUIAS / IMPOSTOS'),(5,'DÉBITO AUTOMÁTICO'),
    (6,'DEPÓSITO BANCÁRIO'),(7,'TED / TRANSFERÊNCIA / PIX'),(8,'CARTÃO DÉBITO'),(9,'CARTÃO CRÉDITO'),(10,'SAQUE'),(11,''),(12,'')
  ) as v(c,n);

  -- TIPOS DE RECEBIMENTO
  insert into tipos_recebimento (empresa_id, codigo, nome)
  select p_empresa, c, n from (values
    (1,'DINHEIRO'),(2,'CARTÃO DÉBITO'),(3,'CARTÃO CRÉDITO'),(4,''),(5,'BOLETOS'),(6,'CHEQUES'),
    (7,'PIX - TED - DEPÓSITO'),(8,'ANTECIPAÇÕES'),(9,'RECEITAS FINANCEIRAS'),(10,'SÓCIOS'),(11,'EMPRÉSTIMOS'),(12,'OUTRAS ENTRADAS')
  ) as v(c,n);

  -- TIPOS DE VENDA (caixa diario)
  insert into tipos_venda (empresa_id, codigo, nome)
  select p_empresa, c, n from (values
    (1,'DINHEIRO'),(2,'CHEQUE PRÉ'),(3,'CHEQUE'),(4,'CREDIÁRIO'),(5,'CARTÃO CRÉDITO'),
    (6,'CARTÃO DÉBITO'),(7,'CONVÊNIO'),(8,'OUTROS'),(9,'PIX'),(10,''),(11,''),(12,'')
  ) as v(c,n);

  -- CODIGOS FAMILIA 1-100
  insert into codigos_familia (empresa_id, codigo, nome, grupo)
  select p_empresa, c, n, g::grupo_familia from (values
    (1,'ÁGUA','MORADIA'),(2,'ELETRODOMÉSTICOS','MORADIA'),(3,'FAXINEIRA','MORADIA'),(4,'GÁS','MORADIA'),(5,'INTERNET','MORADIA'),
    (6,'LUZ','MORADIA'),(7,'MANUTENÇÃO CASA','MORADIA'),(8,'MOBILIÁRIO','MORADIA'),(9,'STREAMING','MORADIA'),(10,'TELEFONE FIXO','MORADIA'),
    (11,'TELEFONE MÓVEL','MORADIA'),(12,'TV POR ASSINATURA','MORADIA'),(13,'UTENSÍLIOS DOMÉSTICOS','MORADIA'),(14,'','MORADIA'),(15,'OUTRAS DESPESAS','MORADIA'),
    (16,'AÇOUGUE','ALIMENTACAO'),(17,'FEIRA / SACOLÃO','ALIMENTACAO'),(18,'PADARIA','ALIMENTACAO'),(19,'REFEIÇÕES FORA','ALIMENTACAO'),(20,'SUPERMERCADO','ALIMENTACAO'),
    (21,'ACADEMIA','PESSOAIS'),(22,'PRESENTES','PESSOAIS'),(23,'SALÃO','PESSOAIS'),(24,'VESTUÁRIO','PESSOAIS'),(25,'','PESSOAIS'),
    (26,'CONSULTAS','SAUDE'),(27,'DENTISTA','SAUDE'),(28,'FARMÁCIA','SAUDE'),(29,'PLANO DE SAÚDE','SAUDE'),(30,'TRATAMENTOS - OUTROS','SAUDE'),
    (31,'FACULDADE','EDUCACAO'),(32,'CURSOS','EDUCACAO'),(33,'ESPORTES','EDUCACAO'),(34,'MATERIAL ESCOLAR / ESTUDO','EDUCACAO'),(35,'VIAGEM / UBER','EDUCACAO'),
    (36,'ACESSÓRIOS ESPORTIVOS','LAZER'),(37,'CLUBE','LAZER'),(38,'LIVROS','LAZER'),(39,'LAZER','LAZER'),(40,'VIAGENS','LAZER'),
    (41,'COMBUSTÍVEL','VEICULOS'),(42,'DESPACHANTE','VEICULOS'),(43,'ESTACIONAMENTO','VEICULOS'),(44,'IPVA','VEICULOS'),(45,'LAVA RÁPIDO','VEICULOS'),
    (46,'LICENCIAMENTO','VEICULOS'),(47,'MANUTENÇÃO VEÍCULOS','VEICULOS'),(48,'MULTAS','VEICULOS'),(49,'PEDÁGIO','VEICULOS'),(50,'SEGURO OBRIGATÓRIO','VEICULOS'),
    (51,'ANUIDADE CARTÃO','FINANCEIRAS'),(52,'EMPRÉSTIMOS','FINANCEIRAS'),(53,'FINANCIAMENTOS','FINANCEIRAS'),(54,'IOF','FINANCEIRAS'),(55,'JUROS / MULTAS','FINANCEIRAS'),
    (56,'MANUTENÇÃO DE CONTA','FINANCEIRAS'),(57,'PARCELAMENTO DE CARTÃO','FINANCEIRAS'),(58,'TARIFAS BANCÁRIAS','FINANCEIRAS'),(59,'','FINANCEIRAS'),(60,'','FINANCEIRAS'),
    (61,'SEGURO AUTOMÓVEL','SEGUROS'),(62,'SEGURO CASA','SEGUROS'),(63,'SEGURO DE VIDA','SEGUROS'),(64,'SEGURO CARTÃO','SEGUROS'),(65,'','SEGUROS'),
    (66,'IPTU','IMPOSTOS'),(67,'IRPF','IMPOSTOS'),(68,'','IMPOSTOS'),(69,'','IMPOSTOS'),(70,'','IMPOSTOS'),
    (71,'ADVOGADO','OUTRAS'),(72,'','OUTRAS'),(73,'','OUTRAS'),(74,'DOAÇÕES','OUTRAS'),(75,'','OUTRAS'),
    (76,'','OUTRAS'),(77,'','OUTRAS'),(78,'','OUTRAS'),(79,'','OUTRAS'),(80,'','OUTRAS'),
    (81,'','OUTRAS'),(82,'','OUTRAS'),(83,'','OUTRAS'),(84,'','OUTRAS'),(85,'','OUTRAS'),
    (86,'','OUTRAS'),(87,'','OUTRAS'),(88,'','OUTRAS'),(89,'','OUTRAS'),(90,'','OUTRAS'),
    (91,'','OUTRAS'),(92,'','OUTRAS'),(93,'','OUTRAS'),(94,'','OUTRAS'),(95,'','OUTRAS'),
    (96,'APLICAÇÕES','INVESTIMENTOS'),(97,'CONSÓRCIO','INVESTIMENTOS'),(98,'IMÓVEIS','INVESTIMENTOS'),(99,'OUTROS INVESTIMENTOS','INVESTIMENTOS'),(100,'POUPANÇA','INVESTIMENTOS')
  ) as v(c,n,g);

  -- Loja matriz padrao
  insert into lojas (empresa_id, nome, is_matriz) values (p_empresa, 'MATRIZ', true);
end $$;
